<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Asset_numbers extends MY_Controller
{
    private $read=array('storage-classification.view','documents.create','documents.edit','document-requests.create','document-requests.edit');
    public function __construct(){parent::__construct();$this->require_login();$this->load->model('Storage_master_model');}
    public function index():void{$this->require_any($this->read);$r=$this->Storage_master_model->assets(dts_page($this->input->get('page')),dts_limit($this->input->get('limit')));$this->render('master/index',array('pageTitle'=>'Asset numbers','entityLabel'=>'Asset number','createUrl'=>site_url('asset_numbers/create'),'columns'=>array('asset_number'=>'Asset number','specific_name'=>'Specific','area_name'=>'Area'),'items'=>$r['items'],'viewBase'=>'asset_numbers/view/'));}
    public function view($id=null):void{$this->require_any($this->read);$id=dts_id_string((string)$id);$row=$id?$this->Storage_master_model->asset($id):null;if(!$row){show_404();return;}$this->render('master/detail',array('pageTitle'=>'Asset number details','row'=>$row));}
    public function create():void{$this->require_any(array('storage-classification.create','storage-classification.manage'));$this->save(null);}
    public function edit($id=null):void{$this->require_any(array('storage-classification.edit','storage-classification.manage'));$this->save(dts_id_string((string)$id));}
    public function delete($id=null):void{$this->require_any(array('storage-classification.delete','storage-classification.manage'));$id=dts_id_string((string)$id);if($id&&$this->input->method(TRUE)==='POST')$this->Storage_master_model->delete_asset($id);redirect('asset_numbers');}
    private function save(?string $id):void{if($this->input->method(TRUE)==='POST'){try{$saved=$this->Storage_master_model->save_asset($id,(string)$this->input->post('asset_number',TRUE),$this->input->post('specific_id',TRUE));redirect('asset_numbers/view/'.$saved);return;}catch(Throwable $e){$this->session->set_flashdata('error',$e->getMessage());}}$row=$id?$this->Storage_master_model->asset($id):array();$this->render('master/form',array('pageTitle'=>$id?'Edit asset number':'Create asset number','formAction'=>site_url($id?'asset_numbers/edit/'.$id:'asset_numbers/create'),'fields'=>array(array('name'=>'asset_number','label'=>'Asset number','value'=>$row['asset_number']??'','required'=>true),array('name'=>'specific_id','label'=>'Specific','type'=>'select','value'=>$row['specific_id']??'','options'=>$this->Storage_master_model->specific_options(),'optionValue'=>'specific_id','optionLabel'=>'specific_name','empty'=>'None'))));}
    private function require_any(array $p):void{foreach($p as $x)if($this->dts_authorization->allows($this->currentUser,$x))return;show_error('Forbidden',403);exit;}
}
