<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Locations extends MY_Controller
{
    private $read=array('location-management.view','storage-classification.view','documents.create','documents.edit','document-requests.create','document-requests.edit');
    public function __construct(){parent::__construct();$this->require_login();$this->load->model('Storage_master_model');}
    public function index():void{$this->require_any($this->read);$r=$this->Storage_master_model->locations(dts_page($this->input->get('page')),dts_limit($this->input->get('limit')));$this->render('master/index',array('pageTitle'=>'Locations','entityLabel'=>'Location','createUrl'=>site_url('locations/create'),'columns'=>array('location_code'=>'Code','location_name'=>'Location','specific_name'=>'Specific','asset_number'=>'Asset','is_active'=>'Active'),'items'=>$r['items'],'viewBase'=>'locations/view/'));}
    public function view($id=null):void{$this->require_any($this->read);$id=dts_id_string((string)$id);$row=$id?$this->Storage_master_model->location($id):null;if(!$row){show_404();return;}$this->render('master/detail',array('pageTitle'=>'Location details','row'=>$row));}
    public function create():void{$this->require_any(array('location-management.create','location-management.manage'));$this->save(null);}
    public function edit($id=null):void{$this->require_any(array('location-management.edit','location-management.manage'));$this->save(dts_id_string((string)$id));}
    public function archive($id=null):void{$this->require_any(array('location-management.archive','location-management.manage'));$id=dts_id_string((string)$id);if($id&&$this->input->method(TRUE)==='POST')$this->Storage_master_model->archive_location($id);redirect('locations');}
    public function delete($id=null):void{$this->archive($id);}
    private function save(?string $id):void{if($this->input->method(TRUE)==='POST'){try{if($id===null)$saved=$this->Storage_master_model->create_location((string)$this->input->post('location_name',TRUE),$this->input->post('asset_id',TRUE),$this->input->post('specific_id',TRUE));else{$this->Storage_master_model->update_location($id,(string)$this->input->post('location_name',TRUE),$this->input->post('asset_id',TRUE),$this->input->post('specific_id',TRUE));$saved=$id;}redirect('locations/view/'.$saved);return;}catch(Throwable $e){$this->session->set_flashdata('error',$e->getMessage());}}$row=$id?$this->Storage_master_model->location($id):array();$this->render('master/form',array('pageTitle'=>$id?'Edit location':'Create location','formAction'=>site_url($id?'locations/edit/'.$id:'locations/create'),'fields'=>array(array('name'=>'location_name','label'=>'Location name','value'=>$row['location_name']??'','required'=>true),array('name'=>'specific_id','label'=>'Specific','type'=>'select','value'=>$row['specific_id']??'','options'=>$this->Storage_master_model->specific_options(),'optionValue'=>'specific_id','optionLabel'=>'specific_name','empty'=>'None'),array('name'=>'asset_id','label'=>'Asset number','type'=>'select','value'=>$row['asset_id']??'','options'=>$this->Storage_master_model->asset_options(),'optionValue'=>'asset_id','optionLabel'=>'asset_number','empty'=>'None'))));}
    private function require_any(array $p):void{foreach($p as $x)if($this->dts_authorization->allows($this->currentUser,$x))return;show_error('Forbidden',403);exit;}
}
