<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Softcopy_categories extends MY_Controller
{
    private $read=array('softcopy-folders.view','softcopy-folders.manage','documents.view','documents.create','documents.edit','document-requests.create','document-requests.edit');
    public function __construct(){parent::__construct();$this->require_login();$this->load->model('Softcopy_category_model');}
    public function index():void{$this->require_any($this->read);$r=$this->Softcopy_category_model->visible(dts_page($this->input->get('page')),dts_limit($this->input->get('limit')),$this->currentUser);$this->render('master/index',array('pageTitle'=>'Softcopy folders','entityLabel'=>'Softcopy folder','createUrl'=>site_url('softcopy_categories/create'),'columns'=>array('category_name'=>'Folder','folder_name'=>'Path','is_active'=>'Active'),'items'=>$r['items'],'viewBase'=>'softcopy_categories/view/'));}
    public function view($id=null):void{$this->require_any($this->read);$id=dts_id_string((string)$id);$row=$id?$this->Softcopy_category_model->find($id,$this->currentUser):null;if(!$row){show_404();return;}$this->render('master/detail',array('pageTitle'=>'Softcopy folder details','row'=>$row));}
    public function create():void{$this->require_any(array('softcopy-folders.create','softcopy-folders.manage'));$this->save(null);}
    public function edit($id=null):void{$this->require_any(array('softcopy-folders.edit','softcopy-folders.manage'));$this->save(dts_id_string((string)$id));}
    public function delete($id=null):void{$this->require_any(array('softcopy-folders.delete','softcopy-folders.manage'));$id=dts_id_string((string)$id);if($id&&$this->input->method(TRUE)==='POST'){try{$this->Softcopy_category_model->delete_category($id,$this->currentUser);$this->session->set_flashdata('success','Folder deleted.');}catch(Throwable $e){$this->session->set_flashdata('error',$e->getMessage());}}redirect('softcopy_categories');}
    private function save(?string $id):void{if($this->input->method(TRUE)==='POST'){try{if($id===null)$saved=$this->Softcopy_category_model->create($this->input->post(NULL,FALSE)?:array(),$this->currentUser);else{$this->Softcopy_category_model->update_category($id,$this->input->post(NULL,FALSE)?:array(),$this->currentUser);$saved=$id;}redirect('softcopy_categories/view/'.$saved);return;}catch(Throwable $e){$this->session->set_flashdata('error',$e->getMessage());}}$row=$id?$this->Softcopy_category_model->find($id,$this->currentUser):array();$this->render('master/form',array('pageTitle'=>$id?'Edit softcopy folder':'Create softcopy folder','formAction'=>site_url($id?'softcopy_categories/edit/'.$id:'softcopy_categories/create'),'fields'=>array(array('name'=>'category_name','label'=>'Folder name','value'=>$row['category_name']??'','required'=>true),array('name'=>'description','label'=>'Description','type'=>'textarea','value'=>$row['description']??''),array('name'=>'parent_category_id','label'=>'Parent folder','type'=>'select','value'=>$row['parent_category_id']??'','options'=>$this->Softcopy_category_model->all_options(),'optionValue'=>'softcopy_category_id','optionLabel'=>'folder_name','empty'=>'Root'))));}
    private function require_any(array $p):void{foreach($p as $x)if($this->dts_authorization->allows($this->currentUser,$x))return;show_error('Forbidden',403);exit;}
}
